services:
  - type: web
    name: expresstire
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py seed_data
    startCommand: gunicorn expresstire.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: expresstire-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: expresstire-db
    plan: free
    databaseName: expresstire
    user: expresstire
