# Generated by Django 5.2.14 on 2026-05-29 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('bundle', 'Bundle Deal')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_qty', models.PositiveIntegerField(default=1, help_text='Minimum tyre qty to qualify')),
                ('code', models.CharField(blank=True, help_text='Discount code (optional)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tyres/')),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Key selling points, one per line')),
                ('tyre_type', models.CharField(choices=[('performance', 'Performance'), ('touring', 'Touring / Comfort'), ('suv', 'SUV / 4x4'), ('light_truck', 'Light Truck / Van'), ('ev', 'Electric Vehicle')], default='performance', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyres', to='tires.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TyreVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_display', models.CharField(help_text='e.g. 225/45R17', max_length=30)),
                ('width', models.PositiveIntegerField()),
                ('aspect', models.PositiveIntegerField()),
                ('diameter', models.PositiveIntegerField()),
                ('load_index', models.CharField(blank=True, max_length=10)),
                ('speed_rating', models.CharField(blank=True, max_length=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='HKD per tyre, includes installation & balancing', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='For showing discounts', max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_qty', models.PositiveIntegerField(default=4, help_text='Number of tyres available')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='e.g. "EV only", "SUV fitment"', max_length=200)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tires.tyre')),
            ],
            options={
                'ordering': ['width', 'aspect', 'diameter'],
                'unique_together': {('tyre', 'size_display')},
            },
        ),
    ]
