# Generated by Django 5.2.14 on 2026-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100)),
                ('caller_phone', models.CharField(max_length=20)),
                ('location', models.TextField(help_text='Vehicle location / address')),
                ('vehicle_info', models.CharField(blank=True, help_text='Car make/model/color', max_length=100)),
                ('service_type', models.CharField(choices=[('flat_tyre', 'Flat Tyre'), ('battery', 'Dead Battery'), ('puncture', 'Puncture Repair'), ('tyre_change', 'Tyre Change'), ('jump_start', 'Jump Start'), ('other', 'Other')], default='flat_tyre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('dispatched', 'Dispatched'), ('on_site', 'On Site'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Call',
                'verbose_name_plural': 'Emergency Calls',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InstallationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('booking_type', models.CharField(choices=[('shop', 'Shop Fitting'), ('mobile', 'Mobile Service')], default='shop', max_length=10)),
                ('shop_location', models.CharField(blank=True, help_text='For shop fitting', max_length=100)),
                ('address', models.TextField(blank=True, help_text='For mobile service')),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(choices=[('08-10', '8:00-10:00 AM'), ('10-12', '10:00-12:00 PM'), ('12-14', '12:00-2:00 PM'), ('14-16', '2:00-4:00 PM'), ('16-18', '4:00-6:00 PM'), ('emergency', 'Emergency / 24hr Mobile')], max_length=10)),
                ('tyre_details', models.CharField(help_text='e.g. Michelin PS5 225/45R17 x4', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(default='Mon-Sat 8:00am-6:00pm', max_length=100)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('map_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
